import Head from 'next/head'
import Layout from "@/components/Layout";
import Image from "next/image";
import profilePic from "../../public/images/profile/developer-pic-1.png"
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import {LinkArrow} from "@/components/Icons";
import HireMe from "@/components/HireMe";
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg"


export default function Home() {
    return (
        <>
            <Head>
                <title>Next Portfolio</title>
                <meta name="description" content="Generated by create next app"/>
            </Head>
            <main className="flex items-center text-dark w-full min-h-screen">
                <Layout className="pt-0">
                    <div className="flex items-center justify-between w-full">
                        <div className="w-1/2">
                            <Image src={profilePic} alt="IA developer image" className="w-full h-auto"/>
                        </div>
                        <div className="w-1/2 flex flex-col items-center self-center">
                            <AnimatedText text="Lorem Ipsum Dolor Sit Amet" className="!text-6xl !text-left"/>
                            <p className="my-4 text-base font-medium">
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                                Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
                                veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                                consequat.
                            </p>
                            <div className="flex items-center self-start mt-2">
                                <Link href="/dummy.pdf"
                                      target="_blank"
                                      className="flex items-center bg-dark text-light
                                       py-2.5 px-6 mr-4 rounded-lg text-lg font-semibold
                                       hover:bg-light hover:text-dark border-2 border-solid border-transparent
                                       hover:border-dark transition-all ease duration-300"
                                      download>
                                    Resume <LinkArrow className={"w-6 ml-1"}/>
                                </Link>
                                <Link href="mailto:abcd@gmail.com" target="_blank"
                                className="ml-4 text-lg font-medium capitalize text-dark underline"
                                >Contact</Link>
                            </div>
                        </div>
                    </div>
                </Layout>
                <HireMe />
                <div className="absolute right-8 bottom-8 w-24 h-auto">
                    <Image src={lightBulb} alt="your name" className="w-full h-auto"/>
                </div>
            </main>
        </>
    )
}
